/**
 * BrightPath v2 starter missions. Independently authored content
 * (Framework §63). Every mission carries governance metadata (§41) and is
 * checked by content/governance.ts in the test suite.
 *
 * Release status is "pilot": content has passed automated checks but still
 * needs professional, editorial and user review before an "approved" claim.
 */
import { GUIDE } from './cast';
import type { Mission } from './types';

const COMMON = {
  version: '2.0.0',
  bands: ['A', 'B', 'C'] as const,
  modalities: ['tap', 'speech', 'aac', 'picture', 'gesture'] as const,
  promptLevels: [1, 2, 3, 5] as const,
  sensoryDefaults: { sound: 'soft', motion: 'full', celebration: 'full' } as const,
  interaction: ['tap'] as const,
  evidenceFields: ['outcome', 'supportLevel', 'modality', 'responseMs', 'toolsUsed', 'context', 'quality'],
  validityRule:
    'Valid when the learner reached the choice with access to all options. Stop/All Done or accidental taps are excluded; Tired check-ins mark opportunities access-limited.',
  accessibility: ['Tap alternative to every drag', 'Audio is never required', 'Colour is never the only signal', 'Reduced Motion supported', 'My Tools always available'],
  reviewStatus: 'pilotReady' as const,
  releaseStatus: 'pilot' as const,
};

export const MISSIONS: Mission[] = [
  {
    ...COMMON,
    bands: [...COMMON.bands],
    modalities: [...COMMON.modalities],
    promptLevels: [...COMMON.promptLevels],
    interaction: [...COMMON.interaction],
    id: 'be-kind-home',
    durationMin: [4, 7],
    questId: 'emotions',
    title: 'Be Kind at Home',
    summary: 'Help Aiden find a calm, helpful choice — then try a kind word at home.',
    goalFamily: 'selfAwareness',
    skillArea: 'emotions',
    intendedGoals: ['choose-support-tool', 'express-kindness'],
    journeyModes: ['discover', 'practice', 'explore'],
    dimensions: ['emergence', 'reliability', 'independence', 'functionalUse'],
    gameEngine: 'kindChoiceStories',
    world: 'Home Hill',
    contextTags: ['home', 'morning routine', 'frustration', 'kindness'],
    realWorldHook: 'Say something kind to a family member today.',
    safetyFlags: [],
    stars: 3,
    badge: 'kind',
    steps: [
      {
        id: 'detail',
        type: 'detail',
        header: 'Today’s Mission',
        title: 'Be Kind at Home',
        body: 'Try saying something kind to a family member today.',
        points: [
          { icon: 'heart', tone: 'blush', title: 'Kindness', sub: 'Make someone feel good' },
          { icon: 'sprout', tone: 'mint', title: 'Real Life Skill', sub: 'Build stronger relationships' },
          { icon: 'people', tone: 'blue', title: 'You Can Do It', sub: 'Small actions make a big difference!' },
        ],
        cta: 'Let’s Try It!',
      },
      {
        id: 'first-then',
        type: 'firstThen',
        title: 'First - Then',
        subtitle: 'Break it down. You’ve got this!',
        first: { art: 'toothbrush', line1: 'Brush', line2: 'my teeth' },
        then: { art: 'foxReading', line1: 'Read', line2: 'a story' },
        tip: 'Small steps help big things happen!',
        cta: 'I’m Ready!',
      },
      {
        id: 'story',
        type: 'story',
        title: 'Aiden’s Story',
        subtitle: 'What would you do?',
        scene: 'bedroom',
        text: 'Aiden is getting ready for school. He can’t find his soccer ball and is feeling frustrated.',
        hint: 'Let’s help Aiden find a calm and helpful solution.',
        cta: 'What should he do?',
      },
      {
        id: 'choice',
        type: 'cardChoice',
        title: 'What should Aiden do?',
        subtitle: 'Choose the best option.',
        cta: 'Next',
        tip: { text: 'Take a moment. Think about what helps!' },
        evidence: { skillArea: 'emotions', templateId: 'choose-support-tool', tags: ['deep-breathing'] },
        options: [
          {
            id: 'breathe',
            label: 'Take a deep breath and look again.',
            art: 'fox',
            tone: 'white',
            helpful: true,
            feedback: 'A deep breath helps our body feel calm — then it’s easier to look again!',
            tags: ['deep-breathing'],
          },
          {
            id: 'yell',
            label: 'Yell and get upset.',
            art: 'aiden',
            tone: 'white',
            helpful: false,
            feedback: 'Big feelings are okay! Yelling might make it harder to find the ball. What could help Aiden feel calm first?',
          },
          {
            id: 'device',
            label: 'Give up and play on a device instead.',
            art: 'device',
            tone: 'white',
            helpful: false,
            feedback: 'A break can help — but the ball is still lost. What could help Aiden keep looking calmly?',
          },
        ],
      },
      {
        id: 'practice',
        type: 'practice',
        kind: 'breathing',
        title: 'Let’s Practice!',
        subtitle: 'Try it together with {buddy}.',
        heading: 'Deep Breathing',
        steps: ['Breathe in slowly… 1, 2, 3', 'Hold for a moment… 1, 2', 'Breathe out slowly… 1, 2, 3'],
        cta: 'Let’s Try It!',
        evidence: { skillArea: 'emotions', templateId: 'choose-support-tool', tags: ['deep-breathing', 'practice'] },
      },
      {
        id: 'feedback',
        type: 'feedback',
        title: 'You Did It!',
        subtitle: 'You chose a kind and helpful solution!',
        badges: [
          { icon: 'heart', line1: 'Kind', line2: 'Choice' },
          { icon: 'sprout', line1: 'Calm', line2: 'Thinking' },
          { icon: 'star', line1: 'Great', line2: 'Effort' },
        ],
        tip: 'Small steps add up to big change!',
        cta: 'Keep Going!',
      },
      {
        id: 'complete',
        type: 'complete',
        title: 'Mission Complete!',
        heading: 'Be Kind at Home',
        message: 'You did it! You practiced kindness today. That’s something to be proud of!',
        checks: ['Tried your best', 'Used a helpful strategy', 'Made a positive choice'],
        cta: 'Awesome!',
      },
      {
        id: 'real-world',
        type: 'realWorld',
        variant: 'family',
        title: 'Real-World Quest',
        questTitle: 'Family Connection',
        quest: 'Say something kind to a family member today.',
        example: 'Try: “Thanks for always being there!”',
        tip: 'Kindness makes stronger families!',
        cta: 'I’ll Do It!',
        setting: 'home',
        evidence: { skillArea: 'communication', templateId: 'express-kindness', tags: ['kindness'] },
      },
    ],
  },
  {
    ...COMMON,
    bands: [...COMMON.bands],
    modalities: [...COMMON.modalities],
    promptLevels: [...COMMON.promptLevels],
    interaction: [...COMMON.interaction],
    id: 'pip-tower',
    durationMin: [3, 6],
    questId: 'friendships',
    title: 'Pip’s Tower',
    summary: 'Pip’s block tower fell. Find kind ways to help a friend.',
    goalFamily: 'social',
    skillArea: 'social',
    intendedGoals: ['respond-to-friend', 'express-kindness'],
    journeyModes: ['discover', 'practice', 'explore'],
    dimensions: ['emergence', 'reliability', 'flexibility'],
    gameEngine: 'kindChoiceStories',
    world: 'Block Room',
    contextTags: ['play', 'peer', 'frustration', 'sharing'],
    realWorldHook: 'Say something kind to a family member today.',
    safetyFlags: [],
    stars: 3,
    badge: 'kind',
    steps: [
      {
        id: 'scene-1',
        type: 'scenario',
        scene: 'playroom',
        text: 'Pip is feeling frustrated because the tower fell down. What could help right now?',
        round: 1,
        rounds: 3,
        cta: 'Let’s choose',
      },
      {
        id: 'choice-1',
        type: 'quickChoice',
        title: 'What would you do?',
        evidence: { skillArea: 'social', templateId: 'respond-to-friend', tags: ['kindness'] },
        options: [
          { id: 'kind-word', label: 'Say a kind and helpful word', icon: 'chat', tone: 'mint', helpful: true, feedback: 'Kind words can help a friend feel better.', modality: 'speech' },
          { id: 'rebuild', label: 'Offer to help rebuild', icon: 'smile', tone: 'sky', helpful: true, feedback: 'Building together can turn a tough moment around.' },
          { id: 'space', label: 'Give Pip some space', icon: 'clock', tone: 'lavender', helpful: true, feedback: 'Sometimes a friend needs a little quiet time. That’s kind too.' },
          { id: 'cheer', label: 'Cheer them up', icon: 'heart', tone: 'blush', helpful: true, feedback: 'A smile or a cheer can show you care.' },
        ],
      },
      {
        id: 'success-1',
        type: 'success',
        title: 'Great Choice!',
        message: 'You showed kindness and support!',
        cta: 'Continue',
        tip: 'Small actions make a big difference!',
      },
      {
        id: 'scene-2',
        type: 'scenario',
        scene: 'playroom',
        text: 'Pip wants to build again, but needs the red block you are using. What could you do?',
        round: 2,
        rounds: 3,
        cta: 'Let’s choose',
      },
      {
        id: 'choice-2',
        type: 'quickChoice',
        title: 'What would you do?',
        evidence: { skillArea: 'social', templateId: 'respond-to-friend', tags: ['sharing'] },
        options: [
          { id: 'share', label: 'Share the red block', icon: 'blocks', tone: 'mint', helpful: true, feedback: 'Sharing helps you both keep building.' },
          { id: 'together', label: 'Ask: “Want to build together?”', icon: 'chat', tone: 'sky', helpful: true, feedback: 'Great idea — building together!', modality: 'speech' },
          { id: 'next', label: 'Say: “You can have it next”', icon: 'clock', tone: 'lavender', helpful: true, feedback: 'Taking turns is fair. You can finish first and then share.' },
          { id: 'hide', label: 'Hide the block', icon: 'question', tone: 'blush', helpful: false, feedback: 'Hiding it might make Pip sad. What’s another way you could both play?' },
        ],
      },
      {
        id: 'scene-3',
        type: 'scenario',
        scene: 'playroom',
        text: 'The new tower is super tall! Pip says, “Thank you for helping!” How could you answer?',
        round: 3,
        rounds: 3,
        cta: 'Let’s choose',
      },
      {
        id: 'choice-3',
        type: 'quickChoice',
        title: 'What would you do?',
        evidence: { skillArea: 'social', templateId: 'respond-to-friend', tags: ['reciprocity'] },
        options: [
          { id: 'welcome', label: 'Say “You’re welcome!”', icon: 'chat', tone: 'mint', helpful: true, feedback: 'Nice answer!', modality: 'speech' },
          { id: 'highfive', label: 'Give a high five', icon: 'highfive', tone: 'sky', helpful: true, feedback: 'High fives say “we did it!”', modality: 'gesture' },
          { id: 'wave', label: 'Smile and wave', icon: 'wave', tone: 'lavender', helpful: true, feedback: 'A smile is a great answer too.', modality: 'gesture' },
          { id: 'again', label: 'Build another one!', icon: 'heart', tone: 'blush', helpful: true, feedback: 'Let’s keep playing!' },
        ],
      },
      {
        id: 'success-3',
        type: 'success',
        title: 'Great Choice!',
        message: 'You showed kindness and support!',
        cta: 'Continue',
        tip: 'Small actions make a big difference!',
      },
      {
        id: 'real-world',
        type: 'realWorld',
        variant: 'card',
        title: 'Real-World Quest',
        questTitle: 'Real-World Quest',
        quest: 'Say something kind to a family member today.',
        tip: 'Kindness makes stronger connections.',
        cta: 'I’ll Do It!',
        setting: 'home',
        evidence: { skillArea: 'communication', templateId: 'express-kindness', tags: ['kindness'] },
      },
    ],
  },
  {
    ...COMMON,
    bands: [...COMMON.bands],
    modalities: [...COMMON.modalities],
    promptLevels: [...COMMON.promptLevels],
    interaction: [...COMMON.interaction],
    id: 'help-hero',
    version: '2.0.1', // guide renamed
    durationMin: [4, 7],
    questId: 'communication',
    title: 'Help Hero',
    summary: 'Asking for help is a super power — practise it your way.',
    goalFamily: 'communication',
    skillArea: 'communication',
    intendedGoals: ['request-help', 'request-break'],
    journeyModes: ['discover', 'practice', 'explore', 'remember'],
    dimensions: ['emergence', 'reliability', 'independence', 'flexibility', 'retention', 'functionalUse'],
    gameEngine: 'helpHero',
    world: 'Library Lane',
    contextTags: ['home', 'school', 'reaching', 'puzzles'],
    realWorldHook: 'Try your Help Power during one real activity today.',
    safetyFlags: [],
    stars: 3,
    badge: 'brave',
    steps: [
      {
        id: 'detail',
        type: 'detail',
        header: 'Today’s Mission',
        title: 'Help Hero',
        body: 'Asking for help is a super power. You can use words, a card or a sign!',
        points: [
          { icon: 'hand', tone: 'blush', title: 'Ask Your Way', sub: 'Words, a Help card or a sign' },
          { icon: 'sprout', tone: 'mint', title: 'Real Life Skill', sub: 'Get what you need' },
          { icon: 'people', tone: 'blue', title: 'You Can Do It', sub: 'Helpers are everywhere!' },
        ],
        cta: 'Let’s Try It!',
      },
      {
        id: 'scene-1',
        type: 'scenario',
        scene: 'shelf',
        text: `${GUIDE.name} wants the book on the top shelf, but can’t reach it. What could ${GUIDE.name} do?`,
        round: 1,
        rounds: 2,
        cta: 'Let’s choose',
      },
      {
        id: 'choice-1',
        type: 'quickChoice',
        title: 'What would you do?',
        evidence: { skillArea: 'communication', templateId: 'request-help', tags: ['help-request'] },
        options: [
          { id: 'ask', label: 'Ask: “Can you help me?”', icon: 'chat', tone: 'mint', helpful: true, feedback: 'Asking with words works great!', modality: 'speech' },
          { id: 'card', label: 'Show my Help card', icon: 'card', tone: 'sky', helpful: true, feedback: 'A Help card is a perfect way to ask.', modality: 'aac' },
          { id: 'point', label: 'Point and look for a grown-up', icon: 'point', tone: 'lavender', helpful: true, feedback: 'Pointing shows what you need. Nice!', modality: 'gesture' },
          { id: 'climb', label: 'Climb up the shelf', icon: 'question', tone: 'blush', helpful: false, feedback: 'Climbing could be unsafe. What’s a safer way to get help?' },
        ],
      },
      {
        id: 'success-1',
        type: 'success',
        title: 'Great Choice!',
        message: 'You found a way to ask for help!',
        cta: 'Continue',
        tip: 'Everyone needs help sometimes!',
      },
      {
        id: 'scene-2',
        type: 'scenario',
        scene: 'puzzle',
        text: 'Pip’s puzzle is really tricky and Pip feels stuck. What could Pip do?',
        round: 2,
        rounds: 2,
        cta: 'Let’s choose',
      },
      {
        id: 'choice-2',
        type: 'quickChoice',
        title: 'What would you do?',
        evidence: { skillArea: 'communication', templateId: 'request-help', tags: ['help-request', 'break'] },
        options: [
          { id: 'help', label: 'Say: “Help, please!”', icon: 'chat', tone: 'mint', helpful: true, feedback: 'Clear and kind — great asking!', modality: 'speech' },
          { id: 'break', label: 'Take a break first', icon: 'clock', tone: 'lavender', helpful: true, feedback: 'A break is a great tool. You can come back when ready.' },
          { id: 'one-more', label: 'Try one more piece', icon: 'smile', tone: 'sky', helpful: true, feedback: 'Trying again is brave. Help is there if you need it.' },
          { id: 'throw', label: 'Throw the puzzle', icon: 'question', tone: 'blush', helpful: false, feedback: 'That feeling is real! Throwing might break the pieces. What could help instead?' },
        ],
      },
      {
        id: 'practice',
        type: 'practice',
        kind: 'helpSignal',
        title: 'Let’s Practice!',
        subtitle: 'Try it together with {buddy}.',
        heading: 'My Help Signal',
        steps: ['Find your Help button', 'Tap it or say “Help, please!”', 'Wait for a helper'],
        cta: 'Let’s Try It!',
        evidence: { skillArea: 'communication', templateId: 'request-help', tags: ['help-request', 'practice'] },
      },
      {
        id: 'feedback',
        type: 'feedback',
        title: 'You Did It!',
        subtitle: 'You asked for help your way!',
        badges: [
          { icon: 'hand', line1: 'Brave', line2: 'Ask' },
          { icon: 'sprout', line1: 'Calm', line2: 'Thinking' },
          { icon: 'star', line1: 'Great', line2: 'Effort' },
        ],
        tip: 'Small steps add up to big change!',
        cta: 'Keep Going!',
      },
      {
        id: 'complete',
        type: 'complete',
        title: 'Mission Complete!',
        heading: 'Help Hero',
        message: 'You practiced asking for help. That’s a real super power!',
        checks: ['Tried your best', 'Used a helpful strategy', 'Asked your way'],
        cta: 'Awesome!',
      },
      {
        id: 'real-world',
        type: 'realWorld',
        variant: 'family',
        title: 'Real-World Quest',
        questTitle: 'Help Power',
        quest: 'Try your Help Power during one real activity today.',
        example: 'Try: “Can you help me, please?”',
        tip: 'Asking for help makes hard things easier!',
        cta: 'I’ll Do It!',
        setting: 'home',
        evidence: { skillArea: 'communication', templateId: 'request-help', tags: ['help-request'] },
      },
    ],
  },
  {
    ...COMMON,
    bands: [...COMMON.bands],
    modalities: [...COMMON.modalities],
    promptLevels: [...COMMON.promptLevels],
    interaction: [...COMMON.interaction],
    id: 'morning-road',
    durationMin: [3, 5],
    questId: 'independence',
    title: 'Routine Road',
    summary: 'Get ready for the day, one tiny step at a time.',
    goalFamily: 'routines',
    skillArea: 'routines',
    intendedGoals: ['short-routine', 'visual-schedule'],
    journeyModes: ['discover', 'practice', 'remember'],
    dimensions: ['emergence', 'reliability', 'independence', 'retention'],
    gameEngine: 'routineRoad',
    world: 'Sunrise Street',
    contextTags: ['home', 'morning', 'sequence'],
    realWorldHook: 'Use your picture steps for one routine today.',
    safetyFlags: [],
    stars: 3,
    badge: 'routine',
    steps: [
      {
        id: 'detail',
        type: 'detail',
        header: 'Today’s Mission',
        title: 'Routine Road',
        body: 'Get ready for the day, one tiny step at a time.',
        points: [
          { icon: 'sun', tone: 'butter', title: 'Morning Steps', sub: 'Wake, wash, dress, go' },
          { icon: 'sprout', tone: 'mint', title: 'Real Life Skill', sub: 'Do more on my own' },
          { icon: 'people', tone: 'blue', title: 'You Can Do It', sub: 'Help is okay any time!' },
        ],
        cta: 'Let’s Try It!',
      },
      {
        id: 'first-then',
        type: 'firstThen',
        title: 'First - Then',
        subtitle: 'Break it down. You’ve got this!',
        first: { art: 'shirt', line1: 'Get', line2: 'dressed' },
        then: { art: 'bowl', line1: 'Eat', line2: 'breakfast' },
        tip: 'Small steps help big things happen!',
        cta: 'I’m Ready!',
      },
      {
        id: 'practice',
        type: 'practice',
        kind: 'sequence',
        title: 'Routine Road',
        subtitle: 'Tap the steps in the order you like to do them.',
        heading: 'My Morning',
        steps: ['Wake up', 'Brush teeth', 'Get dressed', 'Pack backpack'],
        orders: [
          ['Wake up', 'Brush teeth', 'Get dressed', 'Pack backpack'],
          ['Wake up', 'Get dressed', 'Brush teeth', 'Pack backpack'],
        ],
        cta: 'Done!',
        evidence: { skillArea: 'routines', templateId: 'short-routine', tags: ['sequence'] },
      },
      {
        id: 'feedback',
        type: 'feedback',
        title: 'You Did It!',
        subtitle: 'You planned your morning, step by step!',
        badges: [
          { icon: 'sun', line1: 'Morning', line2: 'Star' },
          { icon: 'sprout', line1: 'Tiny', line2: 'Steps' },
          { icon: 'star', line1: 'Great', line2: 'Effort' },
        ],
        tip: 'Small steps add up to big change!',
        cta: 'Keep Going!',
      },
      {
        id: 'complete',
        type: 'complete',
        title: 'Mission Complete!',
        heading: 'Routine Road',
        message: 'You did it! You planned your morning. That’s something to be proud of!',
        checks: ['Tried your best', 'Used your picture steps', 'Did it your way'],
        cta: 'Awesome!',
      },
      {
        id: 'real-world',
        type: 'realWorld',
        variant: 'family',
        title: 'Real-World Quest',
        questTitle: 'Morning Map',
        quest: 'Use your picture steps for one routine today.',
        example: 'Try: point to each step when it’s done!',
        tip: 'Routines help days feel calmer!',
        cta: 'I’ll Do It!',
        setting: 'home',
        evidence: { skillArea: 'routines', templateId: 'short-routine', tags: ['sequence'] },
      },
    ],
  },
  {
    ...COMMON,
    bands: [...COMMON.bands],
    modalities: [...COMMON.modalities],
    promptLevels: [...COMMON.promptLevels],
    interaction: [...COMMON.interaction],
    id: 'flexi-fix',
    version: '2.0.1', // guide renamed
    durationMin: [2, 4],
    questId: 'confidence',
    title: 'Flexi-Fix',
    summary: 'Plans change sometimes. Find another way to have fun.',
    goalFamily: 'flexibility',
    skillArea: 'focus',
    intendedGoals: ['try-another-option', 'handle-small-change'],
    journeyModes: ['practice', 'explore'],
    dimensions: ['reliability', 'flexibility', 'functionalUse'],
    gameEngine: 'flexiFix',
    world: 'Playground Park',
    contextTags: ['outdoors', 'change', 'disappointment'],
    realWorldHook: 'Try one new thing today — a game, a food or a new way home.',
    safetyFlags: [],
    stars: 3,
    badge: 'explorer',
    steps: [
      {
        id: 'scene-1',
        type: 'scenario',
        scene: 'playground',
        text: `The slide is closed today! ${GUIDE.name} really wanted to slide. What could ${GUIDE.name} do?`,
        round: 1,
        rounds: 1,
        cta: 'Let’s choose',
      },
      {
        id: 'choice-1',
        type: 'quickChoice',
        title: 'What would you do?',
        evidence: { skillArea: 'focus', templateId: 'try-another-option', tags: ['flexibility'] },
        options: [
          { id: 'swings', label: 'Try the swings instead', icon: 'swing', tone: 'mint', helpful: true, feedback: 'Swings are fun too! Great flexible thinking.' },
          { id: 'ask', label: 'Ask what else we could do', icon: 'chat', tone: 'sky', helpful: true, feedback: 'Asking for ideas is a smart move.', modality: 'speech' },
          { id: 'feel', label: 'Say: “I feel disappointed”', icon: 'heart', tone: 'lavender', helpful: true, feedback: 'Naming a feeling helps. It’s okay to feel disappointed.' },
          { id: 'leave', label: 'Give up on the park', icon: 'question', tone: 'blush', helpful: false, feedback: 'It’s okay to feel sad. Is there something else fun to try first?' },
        ],
      },
      {
        id: 'success-1',
        type: 'success',
        title: 'Great Choice!',
        message: 'You found another way to have fun!',
        cta: 'Continue',
        tip: 'Trying new things makes you brave!',
      },
      {
        id: 'real-world',
        type: 'realWorld',
        variant: 'card',
        title: 'Real-World Quest',
        questTitle: 'Real-World Quest',
        quest: 'Try one new thing today — a game, a food or a new way home.',
        tip: 'New things help us grow.',
        cta: 'I’ll Do It!',
        setting: 'outdoors',
        evidence: { skillArea: 'focus', templateId: 'try-another-option', tags: ['flexibility'] },
      },
    ],
  },
];

export function missionById(id: string): Mission | undefined {
  return MISSIONS.find((m) => m.id === id);
}

export function missionForQuest(questId: string): Mission | undefined {
  return MISSIONS.find((m) => m.questId === questId);
}
